### ISSUE TITLE
About environment setting

### ISSUE THREAD

**Issue by PreFKim** [gudgud96/MR-MT3#13]
Thank you for your contribution to Music Transcription

I'm interested in your research and I want to apply your model to my custom songs with below code:

```python
    ## test.py main
    # get_scores(
    #     model,
    #     eval_audio_dir=dir,
    #     mel_norm=mel_norm,
    #     eval_dataset=cfg.eval.eval_dataset,
    #     exp_tag_name=cfg.eval.exp_tag_name,
    #     ground_truth_midi_dir=ground_truth_midi_dir,
    #     contiguous_inference=cfg.eval.contiguous_inference,
    #     use_tf_spectral_ops=cfg.eval.use_tf_spectral_ops,
    #     batch_size=cfg.eval.batch_size,
    # )

    handler = InferenceHandler(
        model= model,
        device = "cuda:0",
        mel_norm= mel_norm,
        contiguous_inference=cfg.eval.contiguous_inference,
        use_tf_spectral_ops=cfg.eval.use_tf_spectral_ops,

    )

    for fname in tqdm.tqdm(glob.glob("/mnt/mr/test_wav/*.wav")):
        audio, _ = librosa.load(fname, sr=16000)
        outpath = f"{fname.split('/')[-1].split('.')[0]}.mid"
        handler.inference(
            audio=audio, 
            audio_path=fname, 
            outpath=outpath,
            batch_size=1,
            max_length=1024,
            verbose=True
        )
```

But, In installing environment, I can't install the environment with your envionement.txt

```
The conflict is caused by:
    The user requested protobuf==3.20
    note-seq 0.0.3 depends on protobuf>=3.6.1
    tensorflow 2.11.0 depends on protobuf<3.20 and >=3.9.2
```

Can you check your environment?

**Comment by PreFKim** [comment]
I solve it with python 3.8

```
transformers==4.18.0
torch
librosa==0.9.1
t5==0.9.3
note-seq
pretty-midi==0.2.9
einops==0.4.1
ddsp==3.3.4
tensorflow==2.11
tensorflow-text==2.11
protobuf
numpy==1.22
hydra-core==1.2.0
tensorflow_probability==0.19.0
typing_extensions
torchaudio
pyglove==0.4.2
```

But diffent problem has occured When I run the below code

```bash
# ==== MT3 official checkpoint ==== #
python3 test.py \
    --config-dir="config" \
    --config-name="config_slakh_f1_0.65" \
    model="MT3Net" \
    path="./pretrained/mt3.pth" \
    eval.eval_dataset="Slakh" \
    eval.exp_tag_name="slakh_mt3_official" \
    eval.audio_dir="/data/slakh2100_flac_redux/test/*/mix_16k.wav" \
    eval.midi_dir="/data/slakh2100_flac_redux/test/" \
    hydra/job_logging=disabled \
    eval.is_sanity_check=True   \
    eval.eval_first_n_examples=1 \
    eval.contiguous_inference=False \
    eval.use_tf_spectral_ops=False \
    +eval.load_weights_strict=False \
    # eval.eval_first_n_examples=1 \
```

Error executing job with overrides: ['model=MT3Net', 'path=./pretrained/mt3.pth', 'eval.eval_dataset=Slakh', 'eval.exp_tag_name=slakh_mt3_official', 'eval.audio_dir=/data/slakh2100_flac_redux/test/*/mix_16k.wav', 'eval.midi_dir=/data/slakh2100_flac_redux/test/', 'eval.is_sanity_check=True', 'eval.eval_first_n_examples=1', 'eval.contiguous_inference=False', 'eval.use_tf_spectral_ops=False', '+eval.load_weights_strict=False']
Error locating target 'tasks.mt3_net.MT3Net', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by gudgud96** [comment]
Hi @PreFKim, thank you for your interest. 

The environment is indeed flaky especially having both TensorFlow and PyTorch in one project. How it works for me is to install the libraries in the `requirements.txt` line-by-line. For the conflict you faced, IIRC I worked around it by leaving `protobuf` to be installed at last, and force it to be at `3.20.0`. It does throw warnings but the installation is successful for me.

For the error you show me, I didn't have it and `tasks.mt3_net.MT3Net` is indeed a module in the codebase. I am on Python 3.10, so not sure if that is an issue if you are on Python 3.8.

**Comment by PreFKim** [comment]
The environment is set up line-by-line using the following bash code with Python 3.10:

```bash
conda create --name mrmt3 python==3.10 -y
conda activate mrmt3
python -m pip install --upgrade pip
python -m pip install transformers==4.18.0
python -m pip install torch
python -m pip install librosa==0.9.1
python -m pip install t5==0.9.3
python -m pip install note-seq==0.0.3
python -m pip install pretty-midi==0.2.9
python -m pip install einops==0.4.1
python -m pip install ddsp <- changed : Dont specify version, when installing python 3.10, Because of llvmlite, numba
python -m pip install tensorflow==2.11
python -m pip install tensorflow-text==2.11
python -m pip install protobuf==3.20
python -m pip install numpy==1.23.5 <- changed : Scipy requires numpy>=1.23.5
python -m pip install hydra-core==1.2.0
python -m pip install typing_extensions
python -m pip install torchaudio <- changed : required 
python -m pip install tensorflow_probability==0.19.0  <- changed : tensorflow==2.11 requires downgrading this library 
```

The version of protobuf is fixed to 3.20.

I changed the versions of some libraries because I couldn't ignore the errors that occurred.

When I run the test.sh with below code:

```
# ==== MT3 official checkpoint ==== #
python3 test.py \
    --config-dir="config" \
    --config-name="config_slakh_f1_0.65" \
    model="MT3Net" \
    path="./pretrained/mt3.pth" \
    eval.eval_dataset="Slakh" \
    eval.exp_tag_name="slakh_mt3_official" \
    eval.audio_dir="/data/slakh2100_flac_redux/test/*/mix_16k.wav" \
    eval.midi_dir="/data/slakh2100_flac_redux/test/" \
    hydra/job_logging=disabled \
    eval.is_sanity_check=True   \
    eval.eval_first_n_examples=1 \
    eval.contiguous_inference=False \
    eval.use_tf_spectral_ops=False \
    +eval.load_weights_strict=False \
    # eval.eval_first_n_examples=1 \
```

The same error had occured :

```
Error executing job with overrides: ['model=MT3Net', 'path=./pretrained/mt3.pth', 'eval.eval_dataset=Slakh', 'eval.exp_tag_name=slakh_mt3_official', 'eval.audio_dir=/data/slakh2100_flac_redux/test/*/mix_16k.wav', 'eval.midi_dir=/data/slakh2100_flac_redux/test/', 'eval.is_sanity_check=True', 'eval.eval_first_n_examples=1', 'eval.contiguous_inference=False', 'eval.use_tf_spectral_ops=False', '+eval.load_weights_strict=False']
Error locating target 'tasks.mt3_net.MT3Net', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I didn't change anything in your files.

If you don't mind, could you tell me the versions of the installed libraries?

```bash
pip list
```

**Comment by gudgud96** [comment]
These are my lib version:
```
transformers==4.18.0
torch==2.3.1
librosa==0.10.2.post1
t5==0.9.3
note-seq==0.0.3
pretty-midi==0.2.9
einops==0.7.0
ddsp 3.3.4
tensorflow==2.11
tensorflow-text==2.11
protobuf==3.20
numpy==1.23.5
hydra-core==1.3.2
typing_extensions==4.10.0
torchaudio==2.3.1
tensorflow_probability==0.19.0
```

The error message you have might be incomplete, can you run `HYDRA_FULL_ERROR=1 python3 test.py xxx` and paste the full error log?

**Comment by PreFKim** [comment]
Thank you for your advise, and I found what is wrong exactly.

```

Error executing job with overrides: ['model=MT3Net', 'path=../../../pretrained/mt3.pth', 'eval.eval_dataset=Slakh', 'eval.exp_tag_name=slakh_mt3_official', 'eval.audio_dir=/data/slakh2100_flac_redux/test/*/mix_16k.wav', 'eval.midi_dir=/data/slakh2100_flac_redux/test/', 'eval.is_sanity_check=True', 'eval.eval_first_n_examples=1', 'eval.contiguous_inference=False', 'eval.use_tf_spectral_ops=False', '+eval.load_weights_strict=False']
Traceback (most recent call last):
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 639, in _locate
    obj = getattr(obj, part)
AttributeError: module 'tasks' has no attribute 'mt3_net'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 645, in _locate
    obj = import_module(mod)
  File "/opt/conda/envs/mrmt3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "test/MR-MT3/tasks/mt3_net.py", line 3, in <module>
    import pytorch_lightning as pl
ModuleNotFoundError: No module named 'pytorch_lightning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 648, in _locate
    raise ImportError(
ImportError: Error loading 'tasks.mt3_net.MT3Net':
ModuleNotFoundError("No module named 'pytorch_lightning'")
Are you sure that 'mt3_net' is importable from module 'tasks'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test/MR-MT3/test.py", line 161, in <module>
    main()
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "test/MR-MT3/test.py", line 92, in main
    pl = hydra.utils.instantiate(cfg.model, optim_cfg=cfg.optim)
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 325, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/opt/conda/envs/mrmt3/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'tasks.mt3_net.MT3Net', see chained exception above.
full_key: model
```

Abstract
```
AttributeError: module 'tasks' has no attribute 'mt3_net'
ModuleNotFoundError: No module named 'pytorch_lightning'
```

In this situation, I installed pytorch_lightning and fixed it.

In my opinion, If someone want to use your model, he should install "pytorch-lightning".


Below is my installation code. 

```
conda create --name mrmt3 python==3.10 -y
conda activate mrmt3
python -m pip install --upgrade pip
python -m pip install transformers==4.18.0
python -m pip install torch
python -m pip install librosa==0.9.1
python -m pip install t5==0.9.3
python -m pip install note-seq==0.0.3
python -m pip install pretty-midi==0.2.9
python -m pip install einops==0.4.1
python -m pip install ddsp <- changed : Dont specify version, when installing python 3.10, Because of llvmlite, numba
python -m pip install tensorflow==2.11
python -m pip install tensorflow-text==2.11
python -m pip install protobuf==3.20
python -m pip install numpy==1.23.5 <- changed : Scipy requires numpy>=1.23.5
python -m pip install hydra-core==1.2.0
python -m pip install typing_extensions
python -m pip install torchaudio <- changed : required 
python -m pip install tensorflow_probability==0.19.0  <- changed : tensorflow==2.11 requires downgrading this library 
python -m pip install pytorch_lightning <- changed : for import the model
```

**Comment by gudgud96** [comment]
@PreFKim Thank you for the deciphering. Yes, `lightning` and `pytorch_lightning` is indeed confusing.
I will update the above to the README for ease of installation for other users. Once again thank you!
